package cn.lxh.community.model;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.id
     *
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.name
     *
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.mimetype
     *
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    private String mimetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.image
     *
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    private byte[] image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.id
     *
     * @return the value of picture.id
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.id
     *
     * @param id the value for picture.id
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.name
     *
     * @return the value of picture.name
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.name
     *
     * @param name the value for picture.name
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.mimetype
     *
     * @return the value of picture.mimetype
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    public String getMimetype() {
        return mimetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.mimetype
     *
     * @param mimetype the value for picture.mimetype
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    public void setMimetype(String mimetype) {
        this.mimetype = mimetype == null ? null : mimetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.image
     *
     * @return the value of picture.image
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    public byte[] getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.image
     *
     * @param image the value for picture.image
     * @mbg.generated Sun Mar 08 13:25:12 CST 2020
     */
    public void setImage(byte[] image) {
        this.image = image;
    }
}